on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: fs-chunker
          release-as: 0.1.0
          changelog-types: '[
          {
            "type": "feat",
            "section": "Features",
            "hidden": false
          },
          {
            "type": "fix",
            "section": "Bug Fixes",
            "hidden": false
          },
          {
            "type": "perf",
            "section": "Miscellaneous",
            "hidden": false
          },
          {
            "type": "refactor",
            "section": "Miscellaneous",
            "hidden": false
          },
          {
            "type": "style",
            "section": "Miscellaneous",
            "hidden": false
          },
          {
            "type": "misc",
            "section": "Miscellaneous",
            "hidden": false
          }
          ]'